tasks:
  - name: Compile project
    command: |
      curl --proto '=https' --tlsv1.2 -sSfL "https://git.io/Jc9bH" | bash -s selfinstall; # Install bashbox
      bashbox build --release;
      touch /workspace/.binit;
      gp sync-done compile;
  - name: Open all src/ *.sh files
    command: |
      gp sync-await compile;
      gp ports await 23000 1>/dev/null;
      for file in gitpod.tmux src/main.sh; do {
        gp open "$file";
      } done
      exit;


